config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "welcome#home"
  get('/home',{to: "welcome#home"})


  resources :products do
    
    resources :reviews do
    
    end
    get :liked, on: :collection

    resources :favourites, shallow: true, only: [:create, :destroy]
    get :favourited, on: :collection

    # get :tagged, on: :collection
    # resources :tags
    

  end

  
  resources :likes, only: [:create, :destroy]
  resources :votes, only: [:create, :destroy] do
    get :voted, on: :collection  
  end
  resources :tags, only:[:index, :show]
  resources :favourites, only:[:create]
  resources :users, only:[:new, :create]
  resources :admin
  resource :session, only:[:new, :create, :destroy]
    
end

app/views/shared/_alert.html.erb
<% if flash[:notice].present?%>

<div class="alert alert-success alert-dismissable fade show" role="alert">
    <%= flash[:notice]%>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
</div>

<% elsif flash[:alert].present?%>
<div class="alert alert-warning alert-dismissable fade show" role="alert">
    <%= flash[:alert]%>
    <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-lg navbar-light bg-light d-flex justify-content-between">
<div>
<%=link_to  'Home', root_path%>
|
<%=link_to  'Add Product', new_product_path%>
|
<%=link_to  'View All Products', products_path%>
|
<%=link_to  'View Tags', tags_path%>
|
<%=link_to  'View Votes', voted_votes_path%>
</div>
<div>
        <% if user_signed_in? %>
        Hello <%= current_user.full_name %> | 
        <%= link_to "Logout", session_path, method: :delete,
        data: {confirm: 'Are you sure you want to log out?'}
         %>
        <% else %>
        <%= link_to "Login", new_session_path %> |
        <%= link_to "Sign Up", new_user_path %>
        <% end %>

        <% if user_signed_in? && current_user.is_admin? %>
         |
        <%= link_to 'Admin Panel', admin_index_path, class: 'nav-item' %>
       
         <% end %>
    
</div>
</div>