config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "welcome#home"
  get('/home',{to: "welcome#home"})


  resources :products do
    
    resources :reviews do
    
    end
    get :liked, on: :collection

    resources :favourites, shallow: true, only: [:create, :destroy]
    get :favourited, on: :collection

    # get :tagged, on: :collection
    # resources :tags
    

  end

  
  resources :likes, only: [:create, :destroy]
  resources :votes, only: [:create, :destroy] do
    get :voted, on: :collection  
  end
  resources :tags, only:[:index, :show]
  resources :favourites, only:[:create]
  resources :users, only:[:new, :create]
  resources :admin
  resource :session, only:[:new, :create, :destroy]
    
end

app/models/tag.rb
class Tag < ApplicationRecord

    before_save :downcase_name
    has_many :taggings, dependent: :destroy
    has_many :products, through: :taggings
    validates :name, presence: true, uniqueness:{ case_sensitive: false}
    private
    def downcase_name
        self.name&.downcase!
    end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

    def index
        @tags= Tag.all.order(name: :asc)
       
    end

    def show
        @tag = Tag.find params[:id]
        @products = @tag.products.order(created_at: :desc)
    end
end

app/views/tags/index.html.erb
<h1>All Tags</h1>
<div >
    <%@tags.each do |tag|%>
    <p>
        <%= link_to(tag.name.capitalize, tag_path(tag.id))%>
    </p>
    <%end%>
    
</div>

app/views/tags/show.html.erb
<h2>All products related to the tag <%= @tag.name.capitalize%></h2>


<% @products.each do |product|%>
<div>
<%= link_to(product.title, product_path(product.id))%>
</div>
<%end%>