config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "welcome#home"
  get('/home',{to: "welcome#home"})


  resources :products do
    
    resources :reviews do
    
    end
    get :liked, on: :collection

    resources :favourites, shallow: true, only: [:create, :destroy]
    get :favourited, on: :collection

    # get :tagged, on: :collection
    # resources :tags
    

  end

  
  resources :likes, only: [:create, :destroy]
  resources :votes, only: [:create, :destroy] do
    get :voted, on: :collection  
  end
  resources :tags, only:[:index, :show]
  resources :favourites, only:[:create]
  resources :users, only:[:new, :create]
  resources :admin
  resource :session, only:[:new, :create, :destroy]
    
end

app/models/product.rb
class Product < ApplicationRecord
    
    belongs_to :user, optional: true
    
    before_validation :set_default_price, :set_default_sale_price
    before_save :captitalize_title
    validates :title, presence:true, uniqueness:{case_sensitive:true, message:"please change the title. it sucks"}, confirmation:{case_sensitive:false}, exclusion: {in: ['apple','microsoft','sony'], message: "%{value} is reserved. Please use a diffferent title"}
    validates :description, presence:true, length:{minimum:0}
    validates :price, numericality:{greater_than:0}
    validate :sale_price_less_than_price
    DEFAULT_PRICE = 1


    has_many :taggings, dependent: :destroy
    has_many :tags, through: :taggings


    def self.search(query)
        where("title ILIKE?", "%#{query}%")
        where("description ILIKE?", "%#{query}%")
    end


    def increment_hit_count
        new_hit_count = self.hit_count += 1
        update({hit_count: new_hit_count})
    end

    # def self.search(search_term)
    #     where("first_name LIKE? OR last_name LIKE? OR email LIKE?", "%#{search_term}%","%#{search_term}%","%#{search_term}%")     
    # end

     #ASSOCIATION WITH PRODUCT MODEL
     has_many :reviews, dependent: :nullify #we can choose to destroy the dependents or nullify

     has_many :favourites, dependent: :destroy
     has_many :favouriters, through: :favourites, source: :user

    def tag_names
        self.tags.map(&:name).join(', ')
    end

    def tag_names=(rhs)
        self.tags=rhs.strip.split(/\s*,\s*/).map do|tag_name|
            Tag.find_or_initialize_by(name: tag_name)
        end
    end

    private

    def set_default_price
        self.price ||= DEFAULT_PRICE 
    end

    def set_default_sale_price
        self.sale_price ||=self.price
    end


    def sale_price_less_than_price
        if self.sale_price > self.price
            errors.add(:sale_price, "sale_price: #{self.sale_price} must be lower than #{self.price}")
        end
    end

    def captitalize_title
        if title.capitalize != "#{title[0]}#{title.slice(1,-1)}"
            self.title = title.capitalize
        end
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :find_product, only:[:destroy,:show, :edit, :update ]
    before_action :authorize_user!,only:[:edit,:update,:destroy]
    def new
        @product=Product.new
    end

    def edit
    end

    def liked
        @reviews= current_user.liked_reviews.order(created_at: :desc)
    end

    def destroy
        @product.destroy
        redirect_to products_path
    end
    
    def index
        @products=Product.all.order(title: :ASC)  
        @search_word=""
        @count=@products.count
    end

    def show
        @reviews = @product.reviews.order(created_at: :DESC)
        @review = Review.new
        @review_hide = params
        # @like=@review.likes.find_by(user: current_user)
        @favourite = @product.favourites.find_by_user_id current_user if user_signed_in?
        # @vote = @product.votes.find_by_user_id current_user if user_signed_in?
    end

    def create
        if params[:search]
            @search_word = params[:search]
            @products= Product.where("title ilike?", "%#{@search_word}%")
            @count=@products.count
            render :index
        else
            @product=Product.new product_params
            @product.user = current_user

            if @product.save
                flash[:notice]="Product created successfully."
                redirect_to product_path(@product.id)
            else
                render :new
            end
        end
    end

    def update
        if @product.update product_params
            redirect_to product_path(@product.id), notice: "Product edited successfully."
        else
            render :edit
        end
    end

    private
    def find_product
        @product=Product.find params[:id] 
    end
    def product_params
        params.require(:product).permit(:title, :description, :price, :category, :image, :tag_names)
    end

    def authorize_user!
        redirect_to root_path, alert: 'Not Authorized' unless can?(:crud, @product)
    end
end

app/views/products/edit.html.erb
<%= form_with model:@product, :class=>"form-group", local: true do |form| %>
        <% if @product.errors.present? %>
        <%= @product.errors.full_messages.join(', ')%>
        <% end %>
            <%= label_tag :title %>
            <div class="input-group">
                <%= form.text_field :title, :class=>'form-control', :required=>true %>
             </div>
            <%= label_tag :description %>
            <div class="input-group">
                <%= form.text_area :description, cols:50 , rows:5,  :class=>'form-control', :required=>true %>
             </div>
            <%= label_tag :price %>
            <div class="input-group">
                <%= form.text_field :price, :class=>'form-control' %>
             </div>          
                         <%= label_tag :category %>
            <div class="input-group">
                <%= form.text_field :category, :class=>'form-control' %>
             </div>     <br>
             <%=form.submit  %> 
            <% end %>
            <br><br>

app/views/products/index.html.erb
<!-- <%#=  %> 👈🏻 To have an output we use this tag  -->
    <%= form_with model: @product, local: true do |f| %> 
 <span class="mt-4">
        <%= f.text_field(:search, class: 'form-control',  value:@search_word, :required => true, :oninvalid =>"this.setCustomValidity('Please enter a value')",
 :oninput =>"setCustomValidity('')")%>
 </span>
 <span>
        <% if @search_word%>
            <%= f.submit label_tag="Search", class:"btn-success"%>
        <%else%>
        <%= f.submit label_tag="Search", class:"btn-success"%>
        <%end%>
</span>
    <% end %>

    <h1>All Products</h1>
    <% if @search_word!="" && @count>0%>
        <p>Showing "<%= @count%>" results for "<%= @search_word%>"</p>
    <% elsif @search_word && @count<=0%>    
        <p>No result found for "<%= @search_word%>"</p>
    <%end%>

<%if @products && @search_word%>
    <% @products.each do |product|%>
    <div class="card mt-4">
    <div class="card-body">
    <h2><%= link_to(product.title, product_path(product.id) )%></h2>
    <p> <%= product.description %></p>
    </div>
    </div>
    <% end %>
<%end%>

app/views/products/liked.html.erb
<h1>Liked Reviews</h1>


<% @reviews.each do |review|%>
<div class="card">
<div class="card-body">
<p><%=review.body%></p>
</div>

</div>
<%end%>

app/views/products/new.html.erb
<%= form_with model:@product, :class=>"form-group", local: true do |form| %>
        <% if @product.errors.present? %>
        <%= @product.errors.full_messages.join(', ')%>
        <% end %>
            <%= label_tag :title %>
            <div class="input-group">
                <%= form.text_field :title, :class=>'form-control', :required=>true %>
             </div>
            <%= label_tag :description %>
            <div class="input-group">
                <%= form.text_area :description, cols:50 , rows:5,  :class=>'form-control', :required=>true %>
             </div>
            <%= label_tag :price %>
            <div class="input-group">
                <%= form.text_field :price, :class=>'form-control' %>
             </div>   
             <div>
                <%= form.label :tag_names  %>  
                <%= form.text_field :tag_names  %> 
            </div>          
             <br>

           
             <%=form.submit  label_tag="Submit Product"%>
            <% end %>
            <br><br>

<script>
$(function(){
    $('#product_tag_names').selectize({
        delimeter:',',
        persist: false,
        labelField:'name', //Coulmn name in db
        valueField:'name',//Coulmn name in db
        searchField:'name',//Coulmn name in db
        options: <%= Tag.select(:name).to_json(except:[:id]).html_safe %>,
        // The above line selects only names from tags table and converts them to a json array of objects without including ids and makes sure its a safe_html string
        // options:[{"name":"first tag"},{"name":"second tag"},{"name":"third tag"},{"name":"fourth tag"},{"name":"fifth tag"}, ....]
        
        create :function(input){
            return{
                name:input
            }
        }
    })
})

</script>

app/views/products/show.html.erb
<div class="card mt-4">
<div class="card-body">
<div class="d-flex">
<h3 ><%= @product.title%></h3>
<% if user_signed_in?  && can?(:favourite, @product)%>
          <% if @favourite.present? %>
            <%= link_to '<i class="fa fa-heart m-2"></i>'.html_safe, favourite_path(@favourite), method: :delete %>
          <% else %>
            <%= link_to '<i class="fa fa-heart-o m-2"></i>'.html_safe, product_favourites_path(@product), method: :post %>
          <% end %>
<% end %>
</div>

<p><%= @product.description %></p>
<p>Price: $<%= @product.price %></p>
<div>
    Tags : 
    <% @product.tags.each do |tag|  %> 
        <%= link_to(tag.name, tag_path(tag.id), class:"bg-light p-1")%>
    <%end%>
</div>
<p>Sold by: <%= @product.user&.full_name || "DELETED" %></p>
<small>
<% if can? :crud, @product%>
    <%= link_to("Edit", edit_product_path(@product.id))%>  |
<%end%>
<% if can? :crud, @product%>
    <%= link_to('Delete', product_path(@product.id), remote:false, method: :delete, data: { confirm: 'Are you sure?' } )%>
<%end%>
</small>
</div>
</div>


<h2 class="mt-4">Leave a Review</h2>
<div class='shadow-sm p-3 mb-5 bg-white round'>
    <%= form_with model: [@product, @review], local: true do |f| %>
        <% if @review.errors.full_messages.each do |msg|%>  
            <p class="text-danger">
                <%= msg %>     
            </p>
        <% end %>
    <% end %>
        <div class='form-group col-2'>
            <%= f.label :rating %>
            <%= f.number_field(:rating, class: 'form-control' )%>
        </div>
        <div class='form-group'>
            <%= f.text_area(:body, class: 'form-control', placeholder: 'Your thoughts here' )%>
        </div>
        <%= f.submit class: 'btn btn-primary'%>
        <% end %>
</div>

<%# to show the ratings  %>
<h3>Reviews</h3>
<% @reviews.each do |review|%>
<% if review.hide == false || (can? :crud, review)%>
    <% if review.hide == false%>
        <div class="card">
        <p class="card-body">
        <%= review.body %>
        <br/>
        <span> Rating:</span>
    <% else review.hide == true%>
        <div class="card text-muted">
        <p class="card-body">
        <%= review.body %>
        <span> Rating:</span>
    <%end%>
    <%# display_stars is a helpermethod in reviews_helper %>
    <% p=display_stars(review)%>
    <span>
    <span style="font-size:200%; color:yellow;">
        <%p[0].times do %>
        &starf;
           
        <%end%>
    </span>
    <span style="font-size:200%; color:yellow;">
        <%p[1].times do %>
             &#9734;
        <%end%>
    </span>
    </span>
   
    <% if can? :crud, review %>
        <small>
        <%if review.hide == false%>
            <%= form_with model: [@product, review], :class=>"form-group ml-4", local: true do |form| %>
            <%= form.submit label_tag="Hide Review"%>
            <%end%>
            </small>
            <%end%>
        <%if review.hide == true%>
            <%= form_with model: [@product, review], :class=>"form-group ml-4", local: true do |form| %>
            <%= form.submit label_tag="UnHide Review"%>
            <%end%>
        </small>
    <%end%>
<%end%>

<div class=ml-4>
    Reviewed by:
    <%= review.user&.full_name || "DELETED" %>
</div>
<% if can? :crud, review %>
<p class="ml-4"><%= link_to "Delete",product_review_path(@product,review), method: :delete,data: {confirm: "Are you sure?"} %>
</p>
<%end%>
<div class="ml-4">
    <small>
    <% like_count= review.likes.count%>
    <% if like_count ==0%>
        <% No likes%>
    <% elsif like_count==1%>
         <%= like_count %> Like
    <%else%>
        <%= like_count %> Likes
    <%end%>
    </small>
    <span>
    <%@like=review.likes.find_by(user: current_user)%>
      <%if user_signed_in?  && can?(:like, review)%>
        <% if @like%>
        <%= link_to '<i class="fa fa-thumbs-up"></i>'.html_safe, like_path(@like),method: :delete  %> 
        <% else %>  
        <%= link_to '<i class="fa fa-thumbs-up" style="color:grey"></i>'.html_safe, likes_path(review_id: review.id, product_id: @product.id), method: :post  %> 
        <% end %> 
    <%end%>
    
    </span>
        <span class="ml-4">
            <small>
            <% vote_count= review.votes.count%>

             <% if vote_count==1%>
                <%= vote_count %> Vote
             <% elsif vote_count==0%>
                No votes
             <%else%>
                <%= vote_count %> Votes
             <%end%>
    </small>
    
    <% @vote=review.votes.find_by(user: current_user) %>
    <%if user_signed_in?  && can?(:vote, review)%>
        <% if @vote%>
        <%= link_to '<i class="fa fa-arrow-up ml-1"></i>'.html_safe, vote_path(@vote),method: :delete  %> 
        <% else %>  
        <%= link_to '<i class="fa fa-arrow-up ml-1" style="color:grey"></i>'.html_safe, votes_path(review_id: review.id, product_id: @product.id), method: :post  %> 
        <%end%>
    <%end%>

    </span>
   
</div>


</p>

</p>
</div>
<br/>
<% end %> 
<%end%>